import { createPagesFunctionHandler } from "@react-router/cloudflare";

// @ts-ignore - generated by react-router build
import * as serverBuild from "../build/server";

const handler = createPagesFunctionHandler({
  build: serverBuild,
  getLoadContext: ({ context }) => ({
    cloudflare: {
      env: context.env as CloudflareEnv,
      ctx: context.waitUntil ? context : ({} as ExecutionContext),
    },
  }),
});

export const onRequest: PagesFunction<CloudflareEnv> = handler;
