import { createPagesFunctionHandler } from "@react-router/cloudflare";

// @ts-ignore - generated by react-router build
import * as serverBuild from "../build/server";

const handler = createPagesFunctionHandler({
  build: serverBuild,
  getLoadContext: ({ context }) => context,
});

export const onRequest: PagesFunction<CloudflareEnv> = handler;
