import { createPagesFunctionHandler } from "@react-router/cloudflare";

// @ts-ignore - generated by react-router build
import * as serverBuild from "../build/server";

const handler = createPagesFunctionHandler({
  build: serverBuild,
  getLoadContext: ({ context }) => context,
});

// Cloudflare Pages does not apply public/_headers rules to responses
// generated by a Pages Function — and this whole app is server-rendered
// through this single catch-all function — so security headers have to be
// attached here rather than relying on _headers alone (which still covers
// genuinely static assets under public/).
const SECURITY_HEADERS: Record<string, string> = {
  "X-Frame-Options": "DENY",
  "X-Content-Type-Options": "nosniff",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "Permissions-Policy": "geolocation=(), camera=(), microphone=(), payment=(), usb=()",
  "Strict-Transport-Security": "max-age=63072000; includeSubDomains; preload",
  "Content-Security-Policy":
    "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self'; font-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; object-src 'none'",
};

export const onRequest: PagesFunction<CloudflareEnv> = async (context) => {
  const response = await handler(context);
  const headers = new Headers(response.headers);
  for (const [name, value] of Object.entries(SECURITY_HEADERS)) {
    headers.set(name, value);
  }
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
};
