// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/api/pending-count": {
    params: {};
  };
  "/api/notifications": {
    params: {};
  };
  "/rezerwacje/nowa": {
    params: {};
  };
  "/rezerwacje/:id": {
    params: {
      "id": string;
    };
  };
  "/rezerwacje/:id/edytuj": {
    params: {
      "id": string;
    };
  };
  "/rezerwacje/:id/zmiana": {
    params: {
      "id": string;
    };
  };
  "/ustawienia": {
    params: {};
  };
  "/powiadomienia": {
    params: {};
  };
  "/regulamin": {
    params: {};
  };
  "/admin/dzisiaj": {
    params: {};
  };
  "/admin/rezerwacje": {
    params: {};
  };
  "/admin/panel": {
    params: {};
  };
  "/admin/uzytkownicy": {
    params: {};
  };
  "/admin/sale": {
    params: {};
  };
  "/admin/logi": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/logout" | "/api/pending-count" | "/api/notifications" | "/rezerwacje/nowa" | "/rezerwacje/:id" | "/rezerwacje/:id/edytuj" | "/rezerwacje/:id/zmiana" | "/ustawienia" | "/powiadomienia" | "/regulamin" | "/admin/dzisiaj" | "/admin/rezerwacje" | "/admin/panel" | "/admin/uzytkownicy" | "/admin/sale" | "/admin/logi";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/api.pending-count.ts": {
    id: "routes/api.pending-count";
    page: "/api/pending-count";
  };
  "routes/api.notifications.ts": {
    id: "routes/api.notifications";
    page: "/api/notifications";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/" | "/rezerwacje/nowa" | "/rezerwacje/:id" | "/rezerwacje/:id/edytuj" | "/rezerwacje/:id/zmiana" | "/ustawienia" | "/powiadomienia" | "/regulamin" | "/admin/dzisiaj" | "/admin/rezerwacje" | "/admin/panel" | "/admin/uzytkownicy" | "/admin/sale" | "/admin/logi";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/";
  };
  "routes/rezerwacje.nowa.tsx": {
    id: "routes/rezerwacje.nowa";
    page: "/rezerwacje/nowa";
  };
  "routes/rezerwacje.$id.tsx": {
    id: "routes/rezerwacje.$id";
    page: "/rezerwacje/:id";
  };
  "routes/rezerwacje.$id.edytuj.tsx": {
    id: "routes/rezerwacje.$id.edytuj";
    page: "/rezerwacje/:id/edytuj";
  };
  "routes/rezerwacje.$id.zmiana.tsx": {
    id: "routes/rezerwacje.$id.zmiana";
    page: "/rezerwacje/:id/zmiana";
  };
  "routes/ustawienia.tsx": {
    id: "routes/ustawienia";
    page: "/ustawienia";
  };
  "routes/powiadomienia.tsx": {
    id: "routes/powiadomienia";
    page: "/powiadomienia";
  };
  "routes/regulamin.tsx": {
    id: "routes/regulamin";
    page: "/regulamin";
  };
  "routes/admin.dzisiaj.tsx": {
    id: "routes/admin.dzisiaj";
    page: "/admin/dzisiaj";
  };
  "routes/admin.rezerwacje.tsx": {
    id: "routes/admin.rezerwacje";
    page: "/admin/rezerwacje";
  };
  "routes/admin.panel.tsx": {
    id: "routes/admin.panel";
    page: "/admin/panel";
  };
  "routes/admin.uzytkownicy.tsx": {
    id: "routes/admin.uzytkownicy";
    page: "/admin/uzytkownicy";
  };
  "routes/admin.sale.tsx": {
    id: "routes/admin.sale";
    page: "/admin/sale";
  };
  "routes/admin.logi.tsx": {
    id: "routes/admin.logi";
    page: "/admin/logi";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/api.pending-count": typeof import("./app/routes/api.pending-count.ts");
  "routes/api.notifications": typeof import("./app/routes/api.notifications.ts");
  "routes/_app": typeof import("./app/routes/_app.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/rezerwacje.nowa": typeof import("./app/routes/rezerwacje.nowa.tsx");
  "routes/rezerwacje.$id": typeof import("./app/routes/rezerwacje.$id.tsx");
  "routes/rezerwacje.$id.edytuj": typeof import("./app/routes/rezerwacje.$id.edytuj.tsx");
  "routes/rezerwacje.$id.zmiana": typeof import("./app/routes/rezerwacje.$id.zmiana.tsx");
  "routes/ustawienia": typeof import("./app/routes/ustawienia.tsx");
  "routes/powiadomienia": typeof import("./app/routes/powiadomienia.tsx");
  "routes/regulamin": typeof import("./app/routes/regulamin.tsx");
  "routes/admin.dzisiaj": typeof import("./app/routes/admin.dzisiaj.tsx");
  "routes/admin.rezerwacje": typeof import("./app/routes/admin.rezerwacje.tsx");
  "routes/admin.panel": typeof import("./app/routes/admin.panel.tsx");
  "routes/admin.uzytkownicy": typeof import("./app/routes/admin.uzytkownicy.tsx");
  "routes/admin.sale": typeof import("./app/routes/admin.sale.tsx");
  "routes/admin.logi": typeof import("./app/routes/admin.logi.tsx");
};